### ISSUE TITLE
APL TODO List for Dragonflight

### ISSUE THREAD

**Issue by seanpeters86** [WarcraftPriests/df-shadow-priest#20]
## General
- [x] Should Mind Sear have any more conditions on when to cast it or is the 50 ready requirement enough?
- [x] Shadow Crash hold condition
- [ ] Dark Void hold conditions
- [ ] Should certain spells be held slightly to line up with Dark Ascension? (i.e. Mindgames)
- [ ] Better 4 target support, make sure it makes sense. People will sim this more because of the council fight
- [x] Before using Mind Devourer on DP check if raid event is coming soon with adds
- [ ] Check if movement events coming soon to delay mind flay insanity or void torrent
- [x] MF:I cancel conditions
- [x] Any reason to play around the set bonus?
- [x] Without MFI is there a reason to press Mind Flay with pure spike talented? Dark Evangelism stacks?
- [x] Mind Devourer usage with Mind Sear
- [x] AoE Logic with PL/MFI/etc over Mind Sear

## Opener
- [ ] Void Torrent usage
- [ ] SW:D/MB usage with Inescapable Torment

## Target Conditions
The following spells need checked on target number cutoffs.
- [x] Halo
- [x] Divine Star
- [ ] Void Bolt
- [ ] Void Torrent
- [ ] Unfurling Darkness
- [ ] Damnation
- [ ] Shadow Word: Death with Deathspeaker/Inescapable Torment
- [ ] Max Vampiric Touch with Dark Ascension in AoE

## On-Use Trinkets
Need to put the following into simc properly so that double on use functions as expected.
- [ ] Horn of Valor
- [x] Voidmender's Shadowgem
- [ ] Tome of Unstable Power
- [x] Darkmoon Deck Box: Rime
- [x] Darkmoon Deck Box: Inferno
- [x] Darkmoon Deck Box: Dance
- [ ] Crimson Gladiator's Badge of Ferocity
- [ ] Conjured Chillglobe
- [ ] Iceblood Deathsnare
- [x] Desperate Invoker's Codex
